### ISSUE TITLE
Error while installing pods for ios

### ISSUE THREAD

**Issue by akshitrcrm** [MrHertal/react-native-twilio-phone#12]
CocoaPods could not find compatible versions for pod "react-native-twilio-phone"
In Podfile:
    react-native-twilio-phone (from `../node_modules/react-native-twilio-phone`)

Specs satisfying the `react-native-twilio-phone (from `../node_modules/react-native-twilio-phone`)` dependency were found, but they required a higher minimum deployment target.
Aborting run

My ios target is  13.0. I think in the podspec file the target set is 11.0 but iOS now requires apps to have minimum 13.0.

**Comment by MrHertal** [comment]
Hi,

Try to update your repo with `pod repo update` before `pod install`.

**Comment by akshitrcrm** [comment]
Maybe that would have worked but i did something else like a temporary fix and it worked too.
I checked the podspec file of TwilioVoice iOS repository and there the platform mentioned was 10.0.
So I changed the platform in the react-natieve-twilio-phone.podspec file
 from 11.0 to 10.0 and then did a pod install.

**Comment by MrHertal** [comment]
OK good, whatever works for you.
