### ISSUE TITLE
Build fails while running example app

### ISSUE THREAD

**Issue by Siddharth2212** [MrHertal/react-native-twilio-phone#14]
I am getting this error:
error: Error: Unable to resolve module `@babel/runtime/helpers/interopRequireDefault` from `../src/RNTwilioPhone.ts`: @babel/runtime/helpers/interopRequireDefault could not be found within the project.

I have tried these solutions:  1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules: rm -rf node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
Also tried changing version of this module to "@babel/runtime": "7.0.0-beta.55". I am still getting same issue. Can you please help?

**Comment by MrHertal** [comment]
Hi,

I installed the example app and could not reproduce. Here is what I did:

`git clone git@github.com:MrHertal/react-native-twilio-phone.git && cd react-native-twilio-phone`

`yarn bootstrap`

`yarn example ios`

After some time, example app successfully started in the Simulator.

What command did you try?

I am using node `v12.18.0` and yarn `1.22.10`

**Comment by Siddharth2212** [comment]
Thank you so much. That helped! I was trying to do it some other way. Also is there anyway we can use phone dialer to type number and then use RNTwilioPhone.startCall to make call to that number?

**Comment by MrHertal** [comment]
@Siddharth2212 I am not sure that it's possible this way.
But I know you can start a call from phone application with CallKeep, see [here](https://github.com/react-native-webrtc/react-native-callkeep/blob/master/docs/android-installation.md#android-common-step-installation)
