### ISSUE TITLE
RNTwilioPhone.fetchAccessToken is not a function

### ISSUE THREAD

**Issue by wavemirani** [MrHertal/react-native-twilio-phone#16]
I am trying to integrate call masking using Twilio.
while I am trying to startcall() it returns the error RNTwilioPhone.fetchAccessToken is not a function

const callKeepOptions = {
      ios: {
        appName: 'TwilioPhone Example',
        supportsVideo: false,
      },
      android: {
        alertTitle: 'Permissions required',
        alertDescription: 'This application needs to access your phone accounts',
        cancelButton: 'Cancel',
        okButton: 'OK',
        additionalPermissions: [],
        // Required to get audio in background when using Android 11
        foregroundService: {
          channelId: 'com.app.xxx',
          channelName: 'Foreground service for my app',
          notificationTitle: 'My app is running on background',
        },
      },
  };

  const options = {
    requestPermissionsOnInit: false, // Default: true - Set to false if you want to request permissions manually
  };

async function fetchAccessToken() {
      axios.get('https://xxxxxxxxxx/api/Account/getTwilioToken').then(res => {
        retun res
      }).catch(err => console.log('err>>>>>>', err))
 };

React.useEffect(() => {
        return RNTwilioPhone.initialize(callKeepOptions, fetchAccessToken. options);
      }, []);
      
      
      async function startCall(to, calleeName, from) {
        try {
          await RNTwilioPhone.startCall(to, calleeName, from);
        } catch (e) {
          console.log('e>>>>>>>>>>>',e);
        }
 }

**Comment by MrHertal** [comment]
Hi,

Maybe `RNTwilioPhone` is not initialized yet when you are calling `startCall`.

Can you show the entire component with the call to `startCall`?

**Comment by wavemirani** [comment]
> Hi,
> 
> Maybe `RNTwilioPhone` is not initialized yet when you are calling `startCall`.
> 
> Can you show the entire component with the call to `startCall`?




Hello,
 
also While I am trying to RNTwilioPhone.initialize() it retuns error 'RNTwilioPhone.fetchAccessToken is not a function'
 
import React, {useState} from 'react'
import { View, Text, Button } from "react-native";
import { RNTwilioPhone } from 'react-native-twilio-phone';
import axios from "axios";

export default function TwilioTest() {
  const callKeepOptions = {
      ios: {
        appName: 'TwilioPhone Example',
        supportsVideo: false,
      },
      android: {
        alertTitle: 'Permissions required',
        alertDescription: 'This application needs to access your phone accounts',
        cancelButton: 'Cancel',
        okButton: 'OK',
        additionalPermissions: [],
        // Required to get audio in background when using Android 11
        foregroundService: {
          channelId: 'com.app.xxxxxx',
          channelName: 'Foreground service for my app',
          notificationTitle: 'My app is running on background',
        },
      },
  };

  const options = {
    requestPermissionsOnInit: true, // Default: true - Set to false if you want to request permissions manually
  };


    async function fetchAccessToken1() {
      axios.get('https://xxxxxx.com/api/Account/getTwilioToken').then(res => {
        return RNTwilioPhone.initialize(callKeepOptions, res.data.TwilioToken. options);
      }).catch(err => console.log('err>>>>>>', err))
    };


      React.useEffect(() => {
        fetchAccessToken1()
      }, []);

      async function startCall() {
        try {
          await RNTwilioPhone.startCall('+00123456789');
        } catch (e) {
          console.log(e);
        }
      }
    return (
        <View>
            <Text>Twilio Test</Text>
            <Button title = "call" onPress= {() => startCall()} />
        </View>
    )
}

//===================================================================================

also, I am generating the token from C# throw bellow the attached code

using System;
using System.Collections.Generic;
using Twilio.Jwt.AccessToken;

class Example
{
    static void Main(string[] args)
    {
        // These values are necessary for any access token
        const string twilioAccountSid = "ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        const string twilioApiKey = "SKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        const string twilioApiSecret = "your_secret";

        // These are specific to Voice
        const string outgoingApplicationSid = "APXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        const string identity = "user";

        // Create a Voice grant for this token
        var grant = new VoiceGrant();
        grant.OutgoingApplicationSid = outgoingApplicationSid;

        // Optional: add to allow incoming calls
        grant.IncomingAllow = true;

        var grants = new HashSet<IGrant>
        {
            { grant }
        };

        // Create an Access Token generator
        var token = new Token(
            twilioAccountSid,
            twilioApiKey,
            twilioApiSecret,
            identity,
            grants: grants);

        Console.WriteLine(token.ToJwt());
    }
}

**Comment by MrHertal** [comment]
Thanks @wavemirani,

You are not initializing this module correctly.
Please read the documentation carefully. Then you can check how the module is initialized in the [example app](https://github.com/MrHertal/react-native-twilio-phone/blob/master/example/src/App.tsx).

`fetchAccessToken` is a function that is calling an API endpoint to get a fresh token.
Twilio is providing some [example projects](https://www.twilio.com/docs/voice/voip-sdk/ios/get-started#3-configure-a-server-to-generate-an-access-token-to-be-used-in-the-app) that you can use to create that API endpoint.

**Comment by sumerpalgit** [comment]
Thanks @MrHertal ,

Now, We are getting fetchAccessToken and calling is working. But now we will calling call with masking which twilio provide so can you please advice us on same.

**Comment by MrHertal** [comment]
Hi @sumerpalgit,

What is call with masking? Do you have a link to Twilio documentation that describes it?

**Comment by sumerpalgit** [comment]
Hello @MrHertal 

Here is link for twilio documentation for : https://www.twilio.com/docs/sms/tutorials/masked-numbers-php-laravel

**Comment by MrHertal** [comment]
Sorry @sumerpalgit I cannot help you with this because I have never built call masking.

You should contact Twilio support, I am sure they will help you setting this up.

I will close this issue for now. Let me know if you need help with this package.
