### ISSUE TITLE
SDK Renamed

### ISSUE THREAD

**Issue by mdyu1000** [MrHertal/react-native-twilio-phone#17]
Twilio Voice SDK 6.1.0 rename class, so XCode can't compile.

https://github.com/twilio/twilio-voice-ios/releases/tag/6.1.0

<img width="610" alt="Screen Shot 2021-01-08 at 14 34 16" src="https://user-images.githubusercontent.com/25993814/104001395-8cb00b80-51da-11eb-9f98-d6d0d83ba79e.png">

**Comment by MrHertal** [comment]
Thanks for reporting that issue, I will release a fix in the next few days.

**Comment by mdyu1000** [comment]
I upgrade some dependencies package version, it works.

1. `example/ios/Podfile.lock`
![image](https://user-images.githubusercontent.com/25993814/104081016-f83fba80-5266-11eb-8920-57cdb25b3773.png)

2. `react-native-twilio-phone.podspec`
![image](https://user-images.githubusercontent.com/25993814/104081022-0ee61180-5267-11eb-97aa-c85c934cb56e.png)

3. Change `TwilioVoice` to `TwilioVoiceSDK` in `ios/TwilioPhone.swift` file, except line 1.

My commit diff: https://github.com/MrHertal/react-native-twilio-phone/compare/master...mdyu1000:master
but too much wrap to see, you can refer above.

**Comment by MrHertal** [comment]
Hi @mdyu1000 

I have upgraded Twilio iOS SDK to 6.1: https://github.com/MrHertal/react-native-twilio-phone/releases/tag/v1.4.0

Let me know if you still have an issue.
