### ISSUE TITLE
Enable speaker while call in progress

### ISSUE THREAD

**Issue by josipsarich** [MrHertal/react-native-twilio-phone#23]
Is there a functionality to put call on a speaker?
Something like: toggleSpeakerCall ?

Thanks for your work
Kind regards, Josip

**Comment by MrHertal** [comment]
Hi 👋 

You mean outside of native call UI?
Currently no...

**Comment by se1exin** [comment]
I'm currently trying implement this, will create a PR if I get it to work.

**Comment by MrHertal** [comment]
Thanks @se1exin 👍

Looks like Twilio did that in the QuickStart app:

https://github.com/twilio/voice-quickstart-ios

It could help

**Comment by se1exin** [comment]
Thanks for the pointer @MrHertal. I've raised #24 which adds speaker toggle support.

**Comment by josipsarich** [comment]
@se1exin I think you should keep code structure, like:  
`toggleMuteCall(callSid: string, mute: boolean): void;`

so you should have
`toggleSpeaker(callSid: string, mute: boolean): void;`

but correct me if I'm wrong
Thanks for the support 👍

**Comment by se1exin** [comment]
Thanks for the feedback @josipsarich, however the `callSid` parameter is not needed to toggle the device speaker. Adding it just so that it matches the other function signatures doesn't make much sense to me 😁

**Comment by josipsarich** [comment]
@MrHertal @se1exin I will close this issue, thank you both for the support, and help to resolve this feature :)

**Comment by MrHertal** [comment]
This is now available: https://github.com/MrHertal/react-native-twilio-phone/releases/tag/v1.5.0
