### ISSUE TITLE
Cancel call functionality?

### ISSUE THREAD

**Issue by josaric** [MrHertal/react-native-twilio-phone#28]
Hi, when I click start call using this function

`await RNTwilioPhone.startCall('+00123456789');`

it takes some time to fetch the token, initialize the call a start riniging. Is there a possibility to cancel the call before it even started ringing?

Thanks

**Comment by MrHertal** [comment]
Hi,

Once [TwilioPhone.startCall](https://github.com/MrHertal/react-native-twilio-phone/blob/6230a10f90148bf6397fdab43bed9aef9ac7ccc7/src/RNTwilioPhone.ts#L124) is fired, call is started and you cannot cancel it before `CallRinging` event is dispatched.

You can only cancel right after the [fetchToken](https://github.com/MrHertal/react-native-twilio-phone/blob/6230a10f90148bf6397fdab43bed9aef9ac7ccc7/src/RNTwilioPhone.ts#L117). You will have to make your own copy of `RNTwilioPhone.ts` and override the `startCall` method.

**Comment by josaric** [comment]
For everyone with this issue I recommend to do next:

setState in constructor: callStartedRinging: FALSE

if user clicks hangUp function and call is not established, put callStartedRinging state to TRUE

and then check inside twilioPhoneEmitter event CallRinging or CallConnected if callStartedRinging state is TRUE and just disconnect call with TwilioPhone.disconnectCall(callSid)

```
constructor(props) {
        super(props);
        this.state = {
            callStartedRinging: false,
            callSid: null,
            established: false
        }
}

let self = this;
twilioPhoneEmitter.addListener('CallConnected', (data) => {
            // disconnects call on connected
            if(self.state.callRingingClose) {
                TwilioPhone.disconnectCall(data.callSid);
                TwilioPhone.endCall(data.callSid);
            } else {
                self.setState({established: true, callSid: data.callSid});
            }
        });

twilioPhoneEmitter.addListener('CallRinging', (data) => {
           // disconnects call on ringing
            if(self.state.callRingingClose) {
                TwilioPhone.disconnectCall(data.callSid);
                TwilioPhone.endCall(data.callSid);
            }
        });
```
