### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by calz10** [MrHertal/react-native-twilio-phone#30]
Hi @MrHertal , im not sure if this question suits here yet. would ask if this package could also have the connect method of twilioVoice? 

same with this package: https://github.com/hoxfon/react-native-twilio-programmable-voice
im planning to change the wrapper into your wrapper as it uses callkeep and im not quite sure if its possible also here.
Thank you.

Referrence:
<img width="341" alt="Screen Shot 2021-04-25 at 5 19 48 PM" src="https://user-images.githubusercontent.com/9754952/115988344-da1a8200-a5eb-11eb-9174-1635952af970.png">

**Comment by calz10** [comment]
hi @MrHertal , have tried to fork your repo then updated the params. it dialed successfuly yet when user accepts the call it is not reflecting on the caller side that it have accepted the call. lol.will expirement if it would work. thans

<img width="776" alt="Screen Shot 2021-04-25 at 8 52 55 PM" src="https://user-images.githubusercontent.com/9754952/115994106-37bcc780-a608-11eb-95e3-d25217c59069.png">

**Comment by calz10** [comment]
ah its working lol i just use simulator then voice on same computer. thank you!

**Comment by calz10** [comment]
Reopening this issue.  maybe someone is looking for this too thanks. @MrHertal , hi your wrapper is great could you able allow extra params in startCall method?  thanks

**Comment by MrHertal** [comment]
Hi,

You can use [startCall](https://github.com/MrHertal/react-native-twilio-phone/blob/6230a10f90148bf6397fdab43bed9aef9ac7ccc7/src/index.ts#L32) on the [lower API](https://github.com/MrHertal/react-native-twilio-phone#low-level-api).


Here is the method signature:

`startCall(accessToken: string, params: ConnectParams): void;`

`params` is a key/value object that is passed to Twilio connect method.

**Comment by caldzvalarisolutions** [comment]
Hi @MrHertal,
Have tried your suggestion yep working in development yet. when i try to release version and make a call
im having crash on android , currently im on the latest react version 0.64.0. 
Just wondering if you've tried it also on your release?

thank you. @MrHertal 
 so i've got this log on bugsnag.
 
 ```/apex/com.android.runtime/lib64/bionic/libc.so:564432 abort	
/data/app/~~E8nb_yg2ilKhOaHBSf571g==/com.myappname-oxyiwM3ylEdVVC0oq_i9Fg==/lib/arm64/libtwilio_voice_android_so.so:3754788```

**Comment by calz10** [comment]
Hi @MrHertal,
Have tried your suggestion yep working in development yet. when i try to release version and make a call
im having crash on android note dev is fine , currently im on the latest rn version 0.64.0. 
Just wondering if you've tried it also on your release?

thank you. @MrHertal 
 so i've got this log on bugsnag.
 

<img width="1155" alt="Screen Shot 2021-05-02 at 6 54 32 PM" src="https://user-images.githubusercontent.com/9754952/116810752-2465ab00-ab78-11eb-948c-713eb0d056c1.png">

**Comment by calz10** [comment]
ah, nvm ill close this issue. the proguard just need to be updated as fixed. thanks @MrHertal
