### ISSUE TITLE
How to re-register device token if it is updated or invalidated

### ISSUE THREAD

**Issue by giangnt1** [MrHertal/react-native-twilio-phone#37]
Twilio recommend implementing the following logic to check if the device token is updated or invalidated

```
- Invoke [TwilioVoice registerWithAccessToken:deviceToken:completion] the first time the App is launched
- Store the device token and the current time. This is necessary to determine if the device token has changed
- Implement PKPushRegistryDelegate and check when the token is updated or invalidated. Compare it to the token value stored in 2. If it has changed, invoke[TwilioVoice registerWithAccessToken:deviceToken:completion] and store the new device token value.
- Check when [TwilioVoice registerWithAccessToken:deviceToken:completion] was last invoked. If it has been over 6 months, register the token again to not let it expire.
```
Example: https://github.com/twilio/voice-quickstart-ios/blob/master/ObjcVoiceQuickstart/ViewController.m#L209

How can I implement this with react-native-twilio-phone? Is there any method to check the device token is updated?

**Comment by MrHertal** [comment]
Hi,

This is managed on iOS by RNTwilioPhone [here](https://github.com/MrHertal/react-native-twilio-phone/blob/4689eb1ce16f9db20f0c70ee5e94ae8a608cf929/src/RNTwilioPhone.ts#L173)

When token is updated, [react-native-voip-push-notification](https://github.com/react-native-webrtc/react-native-voip-push-notification) is sending 'register' event. RNTwilioPhone will then fetch a new access token and call the register method.

Same thing happens on Android [here](https://github.com/MrHertal/react-native-twilio-phone/blob/4689eb1ce16f9db20f0c70ee5e94ae8a608cf929/src/RNTwilioPhone.ts#L151), but the event is sent by `react-native-firebase/messaging`

**Comment by giangnt1** [comment]
That means I don't need to do anything, RNTwilioPhone already managed the device token updated event, is that right?
I just got an issue with register/unregister the device token, unable to make a call until I completely remove the application then re-install it and register the token again.  I asked Twilio for help and they suggested implementing the token updated login above.
Do you have any idea?

**Comment by MrHertal** [comment]
Ok are you able to reproduce this issue? Tell me the steps you did so I can reproduce.

Thanks.
