### ISSUE TITLE
Inbound Call Name vs Number

### ISSUE THREAD

**Issue by KendallWeihe** [MrHertal/react-native-twilio-phone#42]
Apologies if this is an inappropriate place to pose this issue. Feel free to point me elsewhere. I have this all setup (thanks @MrHertal!) and functional, but one piece yields a bit of a poor user experience. 

**When a user receives an inbound call** the number coming in just looks like `+11234567890` instead of `John Doe` even if I have a contact in my phone book for that number. 

I didn't go the route in the suggested [Quick Start](https://www.twilio.com/docs/voice/voip-sdk/ios/get-started) by using _Twilio Serverless._ For reasons I won't go into, I have my own server that integrates with TwiML. I bring this up because perhaps I'm having this issue because I'm not providing the right TwiML instruction -- such as `callerId` https://www.twilio.com/docs/voice/twiml/dial#callerid. 

Any ideas?

**Comment by MrHertal** [comment]
Hi, have you tried to set the `callerId`? It should work.
