### ISSUE TITLE
Can I call a number using app

### ISSUE THREAD

**Issue by jamesawer3** [MrHertal/react-native-twilio-phone#49]
Hey Guys,
   I'm new to twilio installed the npm and followed all the steps given in document. I could initiate the call from my mobile and its just playing a song i gave in twiml. I need help in calling from my app to app or normal call.
   
Twiml File:
http://demo.twilio.com/docs/voice.xml

**Comment by MrHertal** [comment]
Hi,

You can check [this function](https://github.com/twilio/voice-quickstart-server-node/blob/master/src/server.js#L68) on the voice-quickstart-server-node project.

It returns a TwiML with a `Dial` verb that redirects call.

**Comment by jamesawer3** [comment]
Thanks I fixed it.
