### ISSUE TITLE
Incoming calls not receiving by the app.  

### ISSUE THREAD

**Issue by mustafa5199** [MrHertal/react-native-twilio-phone#5]
Hi @MrHertal , I used your package to make and receive calls. I have followed all the steps that mentioned in the doc. After that I have successfully make a call to non twilio number. but when I tried to make a incoming call through non twilio number it is unable to make a incoming call on app. Can you help me out in the issue that I am facing.

**Comment by MrHertal** [comment]
Hi,

Twilio documentation describes 3 kinds of call:

[Receive an incoming call](https://www.twilio.com/docs/voice/voip-sdk/ios/get-started#bullet10)
[Make client to client call](https://www.twilio.com/docs/voice/voip-sdk/ios/get-started#bullet11)
[Make client to PSTN call](https://www.twilio.com/docs/voice/voip-sdk/ios/get-started#bullet12)

In your case, you want to make a PSTN call to client?

**Comment by mustafa5199** [comment]
Yes, In my case I want to make a PSTN call to client. Is it possible through twilio ?

**Comment by MrHertal** [comment]
Yes it is possible. It works this way:

People need to dial a phone number that is managed in your Twilio account.
Then some TwiML code handles the call and executes a `Dial` verb that redirects the call to your client.

Follow [this guide](https://www.twilio.com/docs/voice/tutorials/how-to-respond-to-incoming-phone-calls) to create a response to an incoming call.
Then use the [Dial verb](https://www.twilio.com/docs/voice/twiml/client) to redirect the incoming call to a client.

**Comment by mustafa5199** [comment]
Hi, @MrHertal I followed the guide that you send. Also, I tried to use your example to make an incoming call, it does start ringing but didn't receive a call on the Twilio example app.

**Comment by mustafa5199** [comment]
Hi, @MrHertal thanks for the help. It worked. I am able to connect calls between PSTN to Twilio client .
