### ISSUE TITLE
[Enhance] `startCall` function of RNTwilioPhone should allow pass additional params

### ISSUE THREAD

**Issue by trieuduongle** [MrHertal/react-native-twilio-phone#51]
Hi @MrHertal ,

As you can see from the image,

![image](https://user-images.githubusercontent.com/20919532/127741500-994a9276-a33f-48a6-a9d5-521a4f7867a0.png)

`params` could be an object that accept any value (not only 2 params as currently: "from" and "to"), and Twilio functions can use these params to serve its request.

So I think we should update the parameter for `startCall` function, it should look like this, I think.

```javascript
static async startCall(to: string, calleeName?: string, from?: string, additionalParams: ConnectParams = {})
```

If you think that this is correct, could you help me update it?

**Comment by MrHertal** [comment]
Hi 👋 

I guess you are right, you can either submit a PR to make this change or use the lower API method TwilioPhone.startCall directly.

Thanks

**Comment by trieuduongle** [comment]
@MrHertal I created a pull request for it. https://github.com/MrHertal/react-native-twilio-phone/pull/53

To avoid modify previous code too much, I just use spread operator to merge your "params" with my "additionalParams"

**Comment by MrHertal** [comment]
Thanks @trieuduongle :)

I will review it asap.

**Comment by MrHertal** [comment]
I just merged your PR and made a new release. Thanks
