### ISSUE TITLE
Permission Audio not working when Android App killed.

### ISSUE THREAD

**Issue by duypxd** [MrHertal/react-native-twilio-phone#55]
I have a problem when calling, A calls B(Android, kill app) then it seems that the audio permission is no longer active, even though the call is received and accepted but no sound from B transmits to A. A transmits for B is stable.

**Comment by duypxd** [comment]
![image](https://user-images.githubusercontent.com/31473225/129689848-0529bfb0-1928-4245-8d79-89778bbf3a58.png)
when app quit.

**Comment by MrHertal** [comment]
Hi,

Can you reproduce that issue on the example app?

**Comment by duypxd** [comment]
@MrHertal m
Do you have 2 apps?
When B is not opening the app. A calls B then B accepts the call. ( B Receive calls in the background app )
1. A will make a sound, B can hear it.
2. Otherwise B emits sound, A cannot hear it.

**Comment by duypxd** [comment]
@MrHertal 
The Record permission is not registered when the app is in the background. [line 244](https://github.com/MrHertal/react-native-twilio-phone/blob/master/src/RNTwilioPhone.ts#L244)

**Comment by chiphan2008** [comment]
> @MrHertal The Record permission is not registered when the app is in the background. [line 244](https://github.com/MrHertal/react-native-twilio-phone/blob/master/src/RNTwilioPhone.ts#L244)

hi friend,
The RNTwilioPhone.getCallUUID() method not public to use. Plz show me, thanks!
![image](https://user-images.githubusercontent.com/23099708/140852139-5e137699-5aed-4cf9-99fb-3aad09717ca9.png)
