### ISSUE TITLE
Didn't receive incoming call when app is kill/quit

### ISSUE THREAD

**Issue by tristonchai** [MrHertal/react-native-twilio-phone#59]
Hi,

Android failed to receive incoming call when the app is quit/kill state, I did added RNTwilioPhone.handleBackgroundState(); before AppRegistry in index.js, but maybe the handleBackgroundState() has not initialize RNTwilioPhone, so it's not working? i not sure

Please guide me ya, thanks

**Comment by MrHertal** [comment]
Hi, please install 4.1.0 version of react-native-callkeep.

**Comment by tristonchai** [comment]
i currently using 4.2.0

**Comment by MrHertal** [comment]
Yes 4.2.0 is not compatible with this library yet, I am waiting for https://github.com/react-native-webrtc/react-native-callkeep/pull/472 to be merged.

**Comment by tristonchai** [comment]
Nice, u save my day, it worked!! Thanks!!
I spend couple day on this method

now only left the reject call and end call from ios (using react native view instead of callkit, therefore i using RNCallKeep.endAllCalls()), but android didn't end call automatically

do you have any suggestion on this issues?

**Comment by thanhnvpk01168** [comment]
@tristonchai @MrHertal 
Is there an event that listens to know if a call is coming? (foreground)
