### ISSUE TITLE
Incoming Client Call Not Received 

### ISSUE THREAD

**Issue by benminer** [MrHertal/react-native-twilio-phone#6]
Hey MrHertal,

First off, thanks for providing this wonderful package. It is extremely useful. However, I️ am having some issues getting calls to notify on my receiving client. I️ am using purely client to client TwilioVoice calls, and have set that up correctly in my call handler for Twilio.

Following your docs, and VoipPushNotif, I️ _think_ I️ have set up that end correctly as well. As far as I️ can tell, I️ requesting permissions (as I️ accept them), initializing both callKeep and Twilio with a token generated by my server with a user's phone # as the identity. This is also reflected in decoding the JWT token.

The call goes through, and even reaches a CallConnected state (Without any CallKeep UI though). But, it gets weird  as it immediately goes into CallDisconnected with no error. I️ can pull up the Call SID in Twilio and see that I️ got a `NO-ANSWER` state for the call, even though the receiving client never saw a call come through, even in the logs from TwilioVoice. 

Something that did catch my eye though is that in my Twilio console, I️ see two calls, one that is Incoming with a "From" tag of 
`client:{phoneNumber}` and then one right above it with that is Incoming with `client:{phoneNumber}`. It seems that my Incoming call instance is generating another that actually places the call to the client. The latter call is a different callSID completely than the first, being a "child" of it, however, Twilio and RNTwilioPhone are reading the first call SID. My APN tokens are solid as Twilio would have thrown errors for invalid ones earlier in the process. 

![Screen Shot 2020-11-14 at 4 31 12 PM](https://user-images.githubusercontent.com/24834721/99158410-23a78e00-2698-11eb-9998-70b0ae326142.png)'

#### Twilio Call Handler XML
```
<Response>
    <Dial callerId="+1{phone}">
        <Client>+1{phone}</Client>
    </Dial>
</Response>
```

I️ did have to add the following to AppDelegate.m on iOS 14 for VOIP notifications, but no dice. 
```
- (void)pushRegistry:(nonnull PKPushRegistry *)registry didUpdatePushCredentials:(nonnull PKPushCredentials *)pushCredentials forType:(nonnull PKPushType)type {
  [RNVoipPushNotificationManager didUpdatePushCredentials:pushCredentials forType:(NSString *)type];
}
```

#### Init Twilio Phone (callKeepOptions and options are default from README)
• Token is stored in AsyncStorage earlier in this function, so a promise is passed returning the static value.
• After logging in your library, I️ can confirm CallKeep is being initted. 
```
        VoipPushNotification.requestPermissions()

        await RNTwilioPhone.initializeCallKeep(callKeepOptions, () => Promise.resolve(token), options)
```

I️ can confirm I️ am seeing this on my receiving client (physical iPhone) in logs:
```
"[TwilioPhone] Successfully registered for VoIP push notifications"
```

Along with:
```
handleRemoteNotificationsRegistered notification.userInfo = {
    deviceToken = {token};
}
```

Logs when a call is started (caller side):
```
2020-11-14 16:47:56.045660-0600 Parley[51315:992984] [TwilioPhone] Starting call
2020-11-14 16:47:56.070253-0600 Parley[51315:992996] [RNCallKeep][requestTransaction] Requested transaction successfully
2020-11-14 16:47:56.074695-0600 Parley[51315:974541] [RNCallKeep][CXProviderDelegate][provider:performStartCallAction]
2020-11-14 16:47:56.074817-0600 Parley[51315:974541] [RNCallKeep][configureAudioSession] Activating audio session
2020-11-14 16:47:56.162007-0600 Parley[51315:974541] [RNCallKeep][CXProviderDelegate][provider:didActivateAudioSession]
2020-11-14 16:47:56.162170-0600 Parley[51315:974541] [RNCallKeep][configureAudioSession] Activating audio session
2020-11-14 16:47:56.179633-0600 Parley[51315:992879] [TwilioPhone] Activating audio
2020-11-14 16:47:56.179800-0600 Parley[51315:992879] [TwilioPhone] Activating audio
2020-11-14 16:47:56.400593-0600 Parley[51315:974541] [TwilioPhone] Call did start ringing
2020-11-14 16:47:56.557595-0600 Parley[51315:993052] [aurioc] AURemoteIO.h:323:entry: Unable to join I/O thread to workgroup ((null)): 2
2020-11-14 16:47:56.704762-0600 Parley[51315:974541] [TwilioPhone] Call did connect
2020-11-14 16:47:58.652520-0600 Parley[51315:974541] [TwilioPhone] Call disconnected
2020-11-14 16:47:58.711680-0600 Parley[51315:992984] [RNCallKeep][reportEndCallWithUUID] uuidString = dab079d1-ff0f-4b92-9047-a58a840aea8a reason = 2
2020-11-14 16:47:58.753777-0600 Parley[51315:974541] [RNCallKeep][CXProviderDelegate][provider:didDeactivateAudioSession]
2020-11-14 16:47:58.756235-0600 Parley[51315:992996] [TwilioPhone] Deactivating audio
2020-11-14 16:47:58.756384-0600 Parley[51315:992996] [TwilioPhone] Deactivating audio
```

Nothing comes through on callee side, log wise. Not even any errors coming from `didReceiveIncomingPushWithPayload`, which isn't even running. My going theory is that there is some disconnect happening with the Twilio servers pushing to the correct device, as I️ am registering with Twilio on both ends with a phone number as the identifier (EG `+1555555555`) yet the call is looking for a identifier of `client:+15555555555` according to the logs. 

Does anything here stick out to you? 

Thanks for reading, and thanks for your work on this. 

Ben

**Comment by MrHertal** [comment]
Hi,

I appreciate the support! Sorry to read you are having an issue.

I compared your console logs with a client to client call I performed and something is different.

<img width="1155" alt="logs" src="https://user-images.githubusercontent.com/11944221/99179849-927cf980-2721-11eb-9730-7f7576585eed.png">

In your snapshot, there is no `client:` prefixing the child call `FROM`.

This is my TwiML handler:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Dial callerId="client:Larry">
        <Client>Steve</Client>
    </Dial>
</Response>
```

As you can see, `callerId` is prefixed by `client:`.

Maybe that's what causing the issue.

**Comment by benminer** [comment]
> Hi,
> 
> I appreciate the support! Sorry to read you are having an issue.
> 
> I compared your console logs with a client to client call I performed and something is different.
> 
> <img alt="logs" width="1155" src="https://user-images.githubusercontent.com/11944221/99179849-927cf980-2721-11eb-9730-7f7576585eed.png">
> 
> In your snapshot, there is no `client:` prefixing the child call `FROM`.
> 
> This is my TwiML handler:
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <Response>
>     <Dial callerId="client:Larry">
>         <Client>Steve</Client>
>     </Dial>
> </Response>
> ```
> 
> As you can see, `callerId` is prefixed by `client:`.
> 
> Maybe that's what causing the issue.

Thanks for the reply! 

So, this actually didn't solve it, but helped in finding the issue at hand. Twilio does not allow "+" characters as client identifiers  and was scrubbing them, I️ think. The receiver being registered with the "+" was causing the mismatch. Once I️ removed the "+" (and added `client:`) it was discovered the APN cert was expired. Go figure.

**Comment by MrHertal** [comment]
OK good to know, thanks for sharing the solution.

I'll close this issue then.
