### ISSUE TITLE
Question for outgoing call open dialer screen

### ISSUE THREAD

**Issue by saurabh874** [MrHertal/react-native-twilio-phone#62]
Hi @MrHertal 
I start outgoing call from my iPhone to other android or iOS device. it is not moving to native screen(dialer screen) in my phone.
so is it anyway to open dialer screen if i start outgoing call to someone?
please help me.

**Comment by MrHertal** [comment]
Hi, there seems to be no way to achieve that on iOS.

Related issue: https://github.com/MrHertal/react-native-twilio-phone/issues/20
