### ISSUE TITLE
Unregister function not working

### ISSUE THREAD

**Issue by tristonchai** [MrHertal/react-native-twilio-phone#66]
Hi MrHertal,

I want to unregister the phone after sign out (so the phone no longer receive any call), and RNTwilioPhone.initialize() again after i sign in (the phone ready to receive call and can outgoing call)

I did using the function unregister(), but i still receive the call.
Can you guide me how to achieve the above process?

Many Thanks!!

**Comment by MrHertal** [comment]
Hi,

it should work, can you reproduce the issue on the example app?

Thanks.
