### ISSUE TITLE
If the call is placed and ended instantly, still the customer receives the call in iOS

### ISSUE THREAD

**Issue by saurabh874** [MrHertal/react-native-twilio-phone#68]
Hi @MrHertal 
I am facing one issue here If the call is placed and ended instantly, still the customer receives the call in iOS
even i tested in you example it is occurring very very less frequently
so can you please help me out for same.
or is thing can happen in iOS?

**Comment by liemdo** [comment]
We don't get that issue at all. I guess your Javascript side doesn't handle the events correctly.

**Comment by akhil-geekyants** [comment]
Sam issue here.
Works fine on android.

**Comment by heyalexchoi** [comment]
https://github.com/MrHertal/react-native-twilio-phone/issues/28#issuecomment-812691119
