### ISSUE TITLE
Toggle speaker not working on Android

### ISSUE THREAD

**Issue by tristonchai** [MrHertal/react-native-twilio-phone#71]
Hi MrHertal, i have 2 problem when using the package:

1. I did implement Toggle speaker on the app, but i notice it only works on IOS, but not Android, do you have any solution for this issues?

2, this issues only happen on Android, i did using "backToForeground" when the Android phone make voice call, sometime it working, sometime the native callkit screen will back to foreground, do you have any solution for this?

Appreciate if you can provide the solution, Thanks :)

**Comment by MrHertal** [comment]
Sorry for late response,

Have you tried to reproduce this issue with the last version of the example app?
