### ISSUE TITLE
When caller Kill the app from background - the second one callee continues to run the call on their side.

### ISSUE THREAD

**Issue by saurabh874** [MrHertal/react-native-twilio-phone#73]
iOS only: Direct Phone - If during the call, the app is killed from the background, the call does not get ended from customer's end.
How to end call callee side as well.

**Comment by saurabh874** [comment]
@MrHertal  I also tried with example and i am facing same issue. can you please have a look.

**Comment by tristonchai** [comment]
You may can try this way:
- send a silent push notification to callee when caller is end call
- callee side, just trigger end call function when received that silent push notification

Hope this helps you

**Comment by saurabh874** [comment]
@tristonchai 
the problem is caller does not end the call from there side. it just kill the app only. so how can we send silent notification to callee.
and callee get the call just like phone normal call so there is no end call function.
do u have any example if yes, can you please share piece of code?
