### ISSUE TITLE
How can we prevent the call logs to go in the phone book?

### ISSUE THREAD

**Issue by zoolle** [MrHertal/react-native-twilio-phone#84]
I am using this package to hide the client phone number from our staff but every time when I make a call it is registered in the phone book and I am able to see the phone number. Is there an option to avoid this?

**Comment by iarmankhan** [comment]
I too want to hide the logs. Any updates here?

**Comment by zoolle** [comment]
@iarmankhan 

use `includesCallsInRecents: false` in your iOS callKeepOptions for android I don't know how it works

**Comment by MrHertal** [comment]
Hi, thanks @zoolle for sharing that solution. It seems more like a CallKeep feature.
Closing this issue.
