### ISSUE TITLE
Call not coming on archived version

### ISSUE THREAD

**Issue by chetan-sevaro** [MrHertal/react-native-twilio-phone#89]
Hi,
  iOS application is working fine in both debug and release run but after archiving it and testing it, call is not coming to the application. Can you let me know if I maybe missing anything here?

**Comment by rajesh-launchventures** [comment]
@chetan-sevaro Was this issue resolved?
How you got it fixed? Also facing the exact same issue.

**Comment by chetan-sevaro** [comment]
@rajesh-launchventures yes while creating the APN credentials, uncheck the sending to sandbox APN and it should work then.
<img width="872" alt="Screenshot 2022-08-03 at 12 37 05 PM" src="https://user-images.githubusercontent.com/98378688/182610056-c880f92b-ade8-42c2-a45a-0f0bbdb37222.png">
