### ISSUE TITLE
End call button doesn't work

### ISSUE THREAD

**Issue by bradydoll** [MrHertal/react-native-twilio-phone#92]
I have been able to get the example app running and have been able to place outgoing calls from it, however I'm having trouble ending the call from the app. I see this issue in both the iOS simulator and when running on a real iPhone.

When I click on "End call", the iOS call-in-progress indicator (green bubble around the time) goes away, so it appears the call to `RNCallKeep.endAllCalls()` is successful, but the Twilio call does not disconnect and the app's in-progress indicator still shows. It's not until I end the call on the receiving end that the app correctly ends the call.

Before clicking "End call":
<img src="https://user-images.githubusercontent.com/913077/174345221-0a0a329c-4343-465e-b84c-df1b13090526.png" width="150" height="280">

After clicking "End call":
<img src="https://user-images.githubusercontent.com/913077/174345301-18f43e82-7399-4f1f-b905-d6dc756d0003.png" width="150" height="280">

**Comment by dolsem** [comment]
I'm having the same issue on iOS. Sometimes endAllCalls works properly, and sometimes it doesn't

**Comment by 2DTW** [comment]
@dolsem @bradydoll You need to set the callSid in your Call Connected listener. Then in your hangup function, add TwilioPhone.endCall(callSid).

Something like this:


```  
  const [callSid, setCallSid] = useState('')
  const [to, setTo] = React.useState('');
  const [callInProgress, setCallInProgress] = React.useState(false);
  RNTwilioPhone.handleBackgroundState(callKeepOptions);


  React.useEffect(() => {
    return RNTwilioPhone.initialize(callKeepOptions, fetchAccessToken);
  }, []);


  React.useEffect(() => {
    const subscriptions = [
      twilioPhoneEmitter.addListener(EventType.CallConnected, ({callSid}) => {
        setCallSid(callSid)
        setCallInProgress(true);
      }),
      twilioPhoneEmitter.addListener(EventType.CallDisconnected, () => {
        setCallInProgress(RNTwilioPhone.calls.length > 0);
        RNCallKeep.endAllCalls();


      }),
      twilioPhoneEmitter.addListener(
        EventType.CallDisconnectedError,
        (data) => {
          console.log(data);
          setCallInProgress(RNTwilioPhone.calls.length > 0);
          RNCallKeep.endAllCalls();
        }
      ),
    ];


    return () => {
      subscriptions.map((subscription) => {
        subscription.remove();
      });
    };
  }, []);


  function hangup() {
    TwilioPhone.endCall(callSid);
    RNCallKeep.endAllCalls();
    setCallInProgress(RNTwilioPhone.calls.length > 0);
  }

```

**Comment by bradydoll** [comment]
@2DTW Isn't calling `TwilioPhone.endCall()` handled by this library?

In [`/src/RNTwilioPhone.ts`](https://github.com/MrHertal/react-native-twilio-phone/blob/da69d6a71f62e9d8ae0cab61c8ff2ee15827ab05/src/RNTwilioPhone.ts#L335-L341) there is a listener for the `RNCallKeep` 'endCall' event that calls it:
```js
    RNCallKeep.addEventListener('endCall', ({ callUUID }) => {
      const sid = RNTwilioPhone.getCallSid(callUUID);

      sid && TwilioPhone.endCall(sid);

      RNTwilioPhone.removeCall(callUUID);
    });
```

After re-trying the example app, hangup is working for me now. I'm not sure what is different with my initial testing that was causing the issue.

**Comment by tuan-healthcare** [comment]
@bradydoll the root cause because the funtions RNTwilioPhone.getCallSid(callUUID) not working when your app killed. It mean it's only working when app is live or background. I face this issue now.

**Comment by nguyentuanit97** [comment]
the root cause because the funtions RNTwilioPhone.getCallSid(callUUID) not working when your app killed. It mean it's only working when app is live or background. I face this issue now.

**Comment by nguyentuanit97** [comment]
@bradydoll the root cause because the funtions RNTwilioPhone.getCallSid(callUUID) not working when your app killed. It mean it's only working when app is live or background. I face this issue now.
