### ISSUE TITLE
Not able to accept the call when app is killed [iOS]

### ISSUE THREAD

**Issue by chetan-sevaro** [MrHertal/react-native-twilio-phone#98]
Hi, In iOS when app is killed, I am receiving the call but when I press accept, it just opens the app and nothing happens.

**Comment by SunnyBalani92** [comment]
Hi @chetan-sevaro - I m facing the same issue. Is this working for you as you have marked this as closed?
Can you please help me out if its working for you

**Comment by chetan-sevaro** [comment]
Hi 
Yes, I fixed it by listening to the `didLoadWithEvents` event from `react-native-call-keep`. It stores all the events which happened while the app is in a killed state. Please feel free to reach out if you still face the issue.

**Comment by SunnyBalani92** [comment]
Hi @chetan-sevaro , I have to take a different approach but that was also related to call keep event handling. Thanks for the help

**Comment by josaric** [comment]
@chetan-sevaro check AppDelegate.mm if you have set everything like in docs.
I'm using the latest version of the app and I have no problems with outgoing or incoming calls.

**Comment by developersofmen** [comment]
did anyone resolved this, we are facing the same issue
